@Hotelss.API_HostAddress = https://localhost:7262
@token = CfDJ8MWGnpKvu19Pl2aYV_QOD1Ne2Rc4nBcbaBXf4gRU78N_7_7WTQpRk3YDbdUAqwPF3CkuDIeSZKrold1Y7mIM2v4mLEIV3OL2EsXJdgSv_Ua_PL_Wy6jU5oh8G1_8OHJnql1N03EjdPnXbuSF12KUg4FOctKHzhzb4TQOXzMFk8eIk7-M68c8ce4odS4yjdtSwXtZOAiNTuDCVaDoB27YpNfqRqBAho08ahG8s58O6KZsKgQFdW17YK52KhEaR-a9KO3O2o74lKPZL46v4ud97XrRoGvEEySKqBkr4jphuZYPTcAQgjRS4b-ZcUwqhjhix8pZvRAvaJgxElBWtWkuAGVeF7K2lsg6BG8KazSEUFnWJOVNUcRHxELkunb-iNJr4ca4tkvXnCBMyQZbUnMTak5vTOkJ2swQGacR-88ByhxzW7yeCi1GyvsE81e0jKxqC_h1V8YC2Ihtg61QQ4AYmixGuYaUWmGRWtcry4GKPcFd8KhVVqKgVPMGU4UzAkJgPRisfx6Vzm6TfLRvSFj0AeicxA2-NGmccjyOSstunxCF9RvrVnkYoWyReVhirc3o_iS6QuxBwtMcCBGgOHHigLc-e-qDMDdzDobb2nIr3n-ZtMX1_u8wr5HB_gb6vTS4UTifZ7LP3YRBZFtaBCp4Ua7lxvtCNb3374qIOoxWLMlSbk8GlKXp5yeipMYTU2LskTp4zxrfOI-U8rKOMR8v2TY5jh34Bdk3hC5deYJAw830Celfg23d_Tx8NIC_CsTysEa3MoyRseXW3P1ZAfZgN1B92NW04lrwoQClp4xJr4G5
GET {{Hotelss.API_HostAddress}}/api/hotels
//Authorization: Bearer {{token}}
###

GET {{Hotelss.API_HostAddress}}/api/hotels/3

###

DELETE {{Hotelss.API_HostAddress}}/api/hotels/5

###

POST  {{Hotelss.API_HostAddress}}/api/hotels
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nombre": "Hotel Bubalu Creado Por el Owner",
  "Description": "Hotel 3 estrellas en medio del monte.",
  "Category": "Luxury",
  "IsAvailable": true,
  "ContactEmail": "contacto@hotelsandiego.com",
  "ContactNumber": "+34 912 345 678",
  "City": "Madrid",
  "Street": "Calle de la Playa 123",
  "PostalCode": "20-001" 
}

###

PATCH {{Hotelss.API_HostAddress}}/api/hotels/9
Content-Type: application/json

{
  "Nombre": "Hotel Bubalulu",
  "Description": "Hotel 3000 estrellas en medio del monte.",
  "IsAvailable": true
}

###

POST {{Hotelss.API_HostAddress}}/api/hotel/4/rooms
Content-Type: application/json

{
  "Name": "3A",
  "Description": "Piso con acceso especial, buena iluminacion.",
  "Price": 90,
  "Beds": 2 
   
}

###




@hotelId=0
GET {{Hotelss.API_HostAddress}}/api/hotel/4/rooms

###

@roomId=3
GET {{Hotelss.API_HostAddress}}/api/hotel/4/rooms/{{roomId}}

###

DELETE {{Hotelss.API_HostAddress}}/api/hotel/4/rooms

###

POST  {{Hotelss.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###

POST  {{Hotelss.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}