@Hotelss.API_HostAddress = https://localhost:7262
@token = CfDJ8MWGnpKvu19Pl2aYV_QOD1PtemQ90n6BgwS0kKs85aNRiCjiinCQEWBkYoVoqaXEz1XYPqL9uD2d63ZhKdf8_TxlBClDl08N5xAZCHVHwnpZeApsyqC43zTPutV0DiMuAx0P3W83UT6P79dwo7z2kqw9hmgIzfvvEmw-fC1o-WyNsgUTAGtxRJYATNjQNoGuNWKB9cibTrY05Ogra5jZbTJe7CiTIEn3eGXpFVO7hAOfB5Y4WCo8_m2XUsJU-9N4YW7xt2a8pXvUkZkhTlUXhC02pd9cT75NAAUW9uN0llVJ7kgz8WAhu0b6giISaCzhM-tCx9f6qMDAN7Ej3TjpqGrBAGv7W6_c0IjP0cTY4rZi68OsWNHq_iixmz9sT-_f3vL7UoPj1g5e1oX_ttG6ZFZSru4Vd6xGrPbdMVLlL2fiuP1npEuPTnrYKuoZZYCTIeH9-bUBOkFWUKoe8qhjkr2TW20W_zrlSNEULfHWX1613PXJmTLc1-TUaxVlfFoAkfdr7EHm1hadTKk7j08tynIAsYkVFiTp47vycrsY-guogVn67DOOwhH70G5Aj7ZfKu4cDagz8AsbTBqNICEFE9qwoKi6lVI9-aU7OlAEwdrLbmC1vTSgtR4xwLLNAtix99PyLTxAxdQtHXKcrOkLs7sMEtnbNQy5aPD95wTCr9j8bxuoECzR6ZA-ca_twoNsujniM8pzHEKPXHGYprUhkOmt7zbhy_RAueIeqppNYxxkCdWAnf7SAYdtr8CwPWGittvsrOKrzbt7PMtgAYKxQWU8JRA3MMn__cuEf8y3SguS
GET {{Hotelss.API_HostAddress}}/api/hotels
//Authorization: Bearer {{token}}
###

GET {{Hotelss.API_HostAddress}}/api/hotels/3
Authorization: Bearer {{token}}
###

DELETE {{Hotelss.API_HostAddress}}/api/hotels/5

###

POST  {{Hotelss.API_HostAddress}}/api/hotels
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nombre": "Hotel Bubalu Creado Por el Owner",
  "Description": "Hotel 3 estrellas en medio del monte.",
  "Category": "Luxury",
  "IsAvailable": true,
  "ContactEmail": "contacto@hotelsandiego.com",
  "ContactNumber": "+34 912 345 678",
  "City": "Madrid",
  "Street": "Calle de la Playa 123",
  "PostalCode": "20-001" 
}

###

PATCH {{Hotelss.API_HostAddress}}/api/hotels/9
Content-Type: application/json

{
  "Nombre": "Hotel Bubalulu",
  "Description": "Hotel 3000 estrellas en medio del monte.",
  "IsAvailable": true
}

###

POST {{Hotelss.API_HostAddress}}/api/hotel/4/rooms
Content-Type: application/json

{
  "Name": "3A",
  "Description": "Piso con acceso especial, buena iluminacion.",
  "Price": 90,
  "Beds": 2 
   
}

###




@hotelId=0
GET {{Hotelss.API_HostAddress}}/api/hotel/4/rooms

###

@roomId=3
GET {{Hotelss.API_HostAddress}}/api/hotel/4/rooms/{{roomId}}

###

DELETE {{Hotelss.API_HostAddress}}/api/hotel/4/rooms

###

POST  {{Hotelss.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###

POST  {{Hotelss.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}