@Hotelss.API_HostAddress = https://localhost:7262
@token = CfDJ8MWGnpKvu19Pl2aYV_QOD1OJzaYucpBDZJApWjFQGf9olawbMIoN6AyUJZqgmQp-lxeLjyaK2cPmegZHJKmyVr4lN2fAMgA6k1bu-3dnHwQtMSR_RqYfVi_60Sx2r53Yi1RDJP9zqieu2UKVRbo59VuuegQMc5dReXIEQtJWItHAdESmBwvFrTHsU3_z67ZvJD-NhVDtanbaiakVlVohwIazrG8Ckh_qhSPAj1rLABZ9h8BMFLbiKSNREo7Lz97upZqYyeiLJp8TVQnTF8CNVg8JFKC4fLpMpFX5hBTICQ_CqwRazHhNolT-Szv61arDpMqsnTpbLkSpYihynr0rQRSMHexQiqCd9j9meb014LMaaNV4Axil4fg_SH5HLCYCxQP3Lbu1uaM0bDvLBj0gbrvPQcleJYf1IK8_4rR6omNa5guKDHPozqoGkk1gQFhSmqG88un_GVtwEbZLOiDudhwIZzBYfUPVbrdKYL4gSy5wCG8NFaf3dTpwVrWQn5wpSjKdZ2oTE_iuA2ts68T2KTSoOj_lY06lxmZ2mbD2pYcl7eO8fTC8RlBskyhpQEr-7OGj3fBNEtsCpiD_Vge5Vuy2x6vOZwRFuDRFTrexRbs58xG8zYgriPUgMJBKZ3zD2igplW2Vdz_o45flbv873TkTn5NONA5hbPHkDafNEcZiGYqN7bn3NFC_jKJDGCinwSTvdvAIhHUuXC2IGbdpBDaLEs-KJIn5eMFYaTkFs61FqDocDSehmml_NQ2pJ7DXO6MDBUZv71yXiU9bRr670YLHxHVohYwUiSXjEMc-b4VlaNISHrWcXG2p_5lLrF9YMs4MtRX-OZVWT52LSMLstMRtv9PetOs7rP1rtlkq1APMKPu0_2ZDyILQlYVxO8ZbDA
GET {{Hotelss.API_HostAddress}}/api/hotels
//Authorization: Bearer {{token}}
###

GET {{Hotelss.API_HostAddress}}/api/hotels/3
Authorization: Bearer {{token}}
###

DELETE {{Hotelss.API_HostAddress}}/api/hotels/5

###

POST  {{Hotelss.API_HostAddress}}/api/hotels
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nombre": "Owner Hotel",
  "Description": "Hotel 3 estrellas en medio del monte.",
  "Category": "Luxury",
  "IsAvailable": true,
  "ContactEmail": "contacto@hotelsandiego.com",
  "ContactNumber": "+34 912 345 678",
  "City": "Madrid",
  "Street": "Calle de la Playa 123",
  "PostalCode": "20-001" 
}

###

PATCH {{Hotelss.API_HostAddress}}/api/hotels/9
Content-Type: application/json

{
  "Nombre": "Hotel Bubalulu",
  "Description": "Hotel 3000 estrellas en medio del monte.",
  "IsAvailable": true
}

###

POST {{Hotelss.API_HostAddress}}/api/hotel/4/rooms
Content-Type: application/json

{
  "Name": "3A",
  "Description": "Piso con acceso especial, buena iluminacion.",
  "Price": 90,
  "Beds": 2 
   
}

###




@hotelId=0
GET {{Hotelss.API_HostAddress}}/api/hotel/4/rooms
Authorization: Bearer {{token}}
###

@roomId=3
GET {{Hotelss.API_HostAddress}}/api/hotel/4/rooms/{{roomId}}

###

DELETE {{Hotelss.API_HostAddress}}/api/hotel/4/rooms

###

POST  {{Hotelss.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###

POST  {{Hotelss.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}

###

PATCH {{Hotelss.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###
